<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ventanillaunica.gob.mx/ConsultarRespuestaCove" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ConsultarRespuestaCoveService" targetNamespace="http://www.ventanillaunica.gob.mx/ConsultarRespuestaCove">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://www.ventanillaunica.gob.mx/ConsultarRespuestaCove" schemaLocation="ConsultarRespuestaCove_xsd1.xsd"/>
        </xsd:schema>
    </types>
    <message name="solicitarConsultarRespuestaCove">
        <part element="tns:solicitarConsultarRespuestaCove" name="parameters"/>
    </message>
    <message name="solicitarConsultarRespuestaCoveResponse">
        <part element="tns:solicitarConsultarRespuestaCoveResponse" name="parameters"/>
    </message>
    <portType name="ConsultarRespuestaCove">
        <operation name="solicitarConsultarRespuestaCove">
            <input message="tns:solicitarConsultarRespuestaCove"/>
            <output message="tns:solicitarConsultarRespuestaCoveResponse"/>
        </operation>
    </portType>
    <binding name="ConsultarRespuestaCovePortBinding" type="tns:ConsultarRespuestaCove">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="solicitarConsultarRespuestaCove">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="ConsultarRespuestaCoveService">
        <port binding="tns:ConsultarRespuestaCovePortBinding" name="ConsultarRespuestaCovePort">
            <soap:address location="https://www.ventanillaunica.gob.mx/ventanilla/ConsultarRespuestaCoveService"/>
        </port>
    </service>
</definitions>